@extends('layout')

@section('title', 'Reports - Inspection Management System')
@section('reports-active', 'active')

@section('content')
<div class="page-header d-flex justify-content-between align-items-center">
    <div>
        <h1 class="page-title">Reports</h1>
        <p class="text-muted">View and manage inspection reports</p>
    </div>
    <div>
        <a href="{{ route('reports.create') }}" class="btn btn-primary">
            <i class="bi bi-file-earmark-plus"></i> Generate New Report
        </a>
    </div>
</div>

@if(session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
@endif

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Report Number</th>
                        <th>Title</th>
                        <th>Inspection</th>
                        <th>Generated By</th>
                        <th>Generated On</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr>
                        <td><strong>{{ $report->report_number }}</strong></td>
                        <td>{{ $report->title }}</td>
                        <td>
                            <strong>{{ $report->inspection->property->name }}</strong><br>
                            <small class="text-muted">{{ $report->inspection->inspection_number }}</small>
                        </td>
                        <td>{{ $report->generator->name }}</td>
                        <td>{{ $report->created_at->format('M d, Y h:i A') }}</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{{ route('reports.show', $report) }}" class="btn btn-outline-primary" title="View">
                                    <i class="bi bi-eye"></i>
                                </a>
                                <a href="#" class="btn btn-outline-success" title="Download">
                                    <i class="bi bi-download"></i>
                                </a>
                                <button type="button" class="btn btn-outline-danger" title="Delete" 
                                    onclick="if(confirm('Are you sure you want to delete this report?')) { document.getElementById('delete-form-{{ $report->id }}').submit(); }">
                                    <i class="bi bi-trash"></i>
                                </button>
                                <form id="delete-form-{{ $report->id }}" action="{{ route('reports.destroy', $report) }}" method="POST" class="d-none">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" class="text-center py-5">
                            <i class="bi bi-file-earmark-text text-muted" style="font-size: 3rem;"></i>
                            <p class="text-muted mt-3">No reports generated yet</p>
                            <a href="{{ route('reports.create') }}" class="btn btn-primary">
                                <i class="bi bi-file-earmark-plus"></i> Generate Your First Report
                            </a>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if($reports->hasPages())
        <div class="d-flex justify-content-between align-items-center mt-4">
            <div>
                <span class="text-muted">
                    Showing {{ $reports->firstItem() }} to {{ $reports->lastItem() }} of {{ $reports->total() }} reports
                </span>
            </div>
            <nav>
                {{ $reports->links() }}
            </nav>
        </div>
        @endif
    </div>
</div>
@endsection
